apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: seuusuario/frontend:latest  # Altere para sua imagem real
          ports:
            - containerPort: 80
          env:
            - name: BACKEND_URL
              value: http://backend:80

